name: "Build Icons"

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - 'master'
        types: [ opened ]

jobs:
    action:
        name: Build Check Action
        runs-on: ubuntu-latest

        env:
            GH_EMAIL: ${{ secrets.GH_EMAIL }}
            GH_NAME: ${{ secrets.GH_NAME }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14.17.0

            - name: Use node_modules cache
              uses: actions/cache@v2
              id: modules-cache
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                restore-keys: ${{ runner.os }}-modules-

            - name: Install dependencies
              if: steps.modules-cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

            - name: Install fontforge
              run: sudo apt-get install fontforge ttfautohint

            - name: Build
              run: npx grunt --FIGMA_TOKEN=${FIGMA_TOKEN}

